### ISSUE TITLE
Dallas Edition Location Voting

### ISSUE THREAD

**Issue by dcousineau** [jmikola/wurstcon.com#4]
A few suggestions suggestions were provided by the ineffable @jasrags:
1. ~~[Jörg's Cafe Vienna](http://jorgscafevienna.com/) ~20min [⭐️⭐️⭐️⭐️](http://www.yelp.com/biz/jorgs-cafe-vienna-plano)~~
2. ~~[Kuby's Sausage House](http://kubys.com/) ~25min [⭐️⭐️⭐️⭐️](http://www.yelp.com/biz/kubys-sausage-house-dallas)~~
3. ~~[Bavarian Grill](http://www.bavariangrill.com/) ~20 min [⭐️⭐️⭐️⭐️](http://www.yelp.com/biz/bavarian-grill-plano)~~
4. [The Blind Butcher](http://theblindbutcher.com/) ~28 min [⭐️⭐️⭐️⭐️](http://www.yelp.com/biz/blind-butcher-dallas)

**Edit** I think we're all decided on The Blind Butcher. Now it's time to figure out our time schedules!

**Comment by dcousineau** [comment]
My personal vote is **The Blind Butcher**. It's closer to downtown and fun shit. Jörg's is in Downtown Plano which is okay~ and we can take a train into fun shit if possible. Also I've heard good things about the blind butcher.

**Comment by Jasrags** [comment]
+1 Blind Butcher. Looks yummy.

**Comment by jmikola** [comment]
Blind Butcher looks like a fantastic choice. The outdoor space seems like a nice option, too.

I realize they don't take reservations, but should one of the local guys check this out and ensure it's a viable option? I don't mind waiting to sit, but it'd suck to run into a logistical problem the day of. Hopefully Sunday afternoon would be relatively light.

**Comment by Jasrags** [comment]
We can do a test run and inquire about a larger party. Do you have an
estimate on the party size?

**Comment by jmikola** [comment]
Let's shoot for 20 (about what we had at True North).

**Comment by dragonmantank** [comment]
Blind Butcher is good for me.

**Comment by GeeH** [comment]
BLIND BUTCHER BCOS I WANT TO BE POPULAR AND VOTE WHAT ALL THE KOOL KIDS VOTE FOR!!!

**Comment by jmikola** [comment]
/ping @dcousineau: Did we confirm a time? Noon?
