### ISSUE TITLE
DC Edition (#2) Location Voting

### ISSUE THREAD

**Issue by xiehan** [jmikola/wurstcon.com#5]
phpWorld 2016 is coming up in a couple of months, and as a self-professed foodie who's trawled the DC food scene extensively, I thought I'd make a few suggestions! (By the way, I'm highly amused y'all went to [Char Bar](http://wurstcon.com/event/2015/koshercon-2015/) last year because I literally live across the street from that place.)

My thinking was that DC's local sausage specialty is the [half-smoke](https://en.wikipedia.org/wiki/Half-smoke), so we really should go to a place that features it. These are the main options:
1. [HalfSmoke](http://halfsmoke.com/) (Shaw-Howard Metro Stop) [no reviews yet](https://www.yelp.com/biz/halfsmoke-washington)
   - opening next month
   - chef has previously won the James Beard award
2. [DCity Smokehouse](http://dcitysmokehouse.com/) (NoMa-Gallaudet U Metro Stop) [:star::star::star:](https://www.yelp.com/biz/dcity-smokehouse-washington-4) 
   - winner of [DC's Best Half-Smoke 2015](http://legacy.washingtoncitypaper.com/bestofdc/foodanddrink/2015/best-half-smoke)
3. [Ben's Chili Bowl](http://benschilibowl.com/) (Union Station Metro Stop, then take the H St streetcar) [:star::star::star:](https://www.yelp.com/biz/bens-chili-bowl-washington-4)
   - has multiple locations, but I'd suggest the H St one over the U St one because:
     - it's less of a tourist destination
     - there is a bar upstairs called [Ten01](https://www.yelp.com/biz/ten-01-washington) which, among other things, features a Manhattan with half-smoke-infused bourbon
   - considered the "classic" place for half-smokes; helped ignite the "craze"

I wouldn't be too put off by the Yelp stars. DC is a tough town for food reviews and most good places that aren't hipster foodie destinations have 3~3.5 stars at best. Personally I'd go with one of the first two options (the HalfSmoke announcement was what got me thinking about WurstCon in the first place) rather than Ben's Chili Bowl because the latter is a bit overrated IMO, but it felt unfair not to include it in a list of places with half-smokes.

Other suggestions welcome, though!

**Comment by jmikola** [comment]
Thanks for the well-research proposal, @xiehan!

@dragonmantank: Since you're speaking at World this year, can I delegate you to run point on this with @EliW?

**Comment by dragonmantank** [comment]
Possibly. I'll know better once we get travel and everything scheduled.

**Comment by dragonmantank** [comment]
I think I'm leaning toward HalfSmoke. DCity Smokehouse looks pretty good but, but HalfSmoke looks like it specializes in sausages. Plus it looks like it can fit a decent amount of people.

I _think_ some people went to Ben's last year after the conference, but I don't think there was anything official. I could be wrong on that, because I think I left [world] on the last day last year.

**Comment by jmikola** [comment]
@xiehan: Can you bump this once HalfSmoke is open for business?

**Comment by xiehan** [comment]
@jmikola: Will do! It's not clear to me what their status is, but I'll be over in that area anyway on 9/10, so if necessary I will do some reconnaissance then.

**Comment by xiehan** [comment]
HalfSmoke is opening tomorrow (October 4th): https://www.washingtonian.com/2016/09/27/halfsmoke-opens-shaw-things-millennials-love/
The thought of smoked elk sausage is making my mouth water...

**Comment by EliW** [comment]
Hey guys ... there is potentially an easier option that I just ran into.

Tyson's Biergarten - http://tysonsbiergarten.com

It's literally just a 24 minute walk right down the road from the venue (Or you can hop the metro one stop).   So you could easily do it there.  Without having to worry about sending everyone on the Metro.   If you are interested in doing that, I'd be super down with it and would link it up on the website as a 'real thing'

https://www.google.com/maps/dir/Sheraton+Tysons+Hotel,+Leesburg+Pike,+Tysons,+VA/Tysons+Biergarten,+Leesburg+Pike,+Tysons,+VA/@38.9259277,-77.2433763,16z/data=!3m1!4b1!4m14!4m13!1m5!1m1!1s0x89b64a60ebecb0cf:0xdb0c351febd04cf8!2m2!1d-77.246181!2d38.9309749!1m5!1m1!1s0x89b64af108344e07:0x2277a6c11915f9ee!2m2!1d-77.2320109!2d38.9212486!3e2

Y'alls call of course.  But when I saw that, Heather screamed WURSTCON!

**Comment by EliW** [comment]
Here's their food menu ... it's 90% sausage: http://tysonsbiergarten.com/#foobox-3/0/foodmenu

**Comment by dragonmantank** [comment]
Looks like HalfSmoke has issues with customer service now that it's open, the Yelp! reviews all seem to indicate the food is good but the service stinks. DCity is now closed for reservations, so that takes them out. 

The Biergarten also has a moonbounce...

I'm fine with Biergaten, it looks like it should have plenty of space (though I'll call ahead), decent food selection, and like Eli said is very close to the venue.

**Comment by jmikola** [comment]
@dragonmantank: Can we get a PR on a new entry for Friday's WurstCon?

**Comment by dragonmantank** [comment]
I will make one later tonight!
